name: Reset Submission

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email to reset submission'
        required: true

jobs:
  reset_submission:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Reset Submission
        run: |
          EMAIL="${{ github.event.inputs.email }}"
          FILE_PATH="responses/${EMAIL}.json"

          if [ -f "$FILE_PATH" ]; then
            rm "$FILE_PATH"
            echo "Submission reset successfully."
          else
            echo "No submission found for this email."
          fi